### ISSUE TITLE
Compile error with esp-idf-6.0 when LWIP_USE_EXTERNAL_MBEDTLS=1 (IDFGH-17678)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-lwip#87]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

It was working when build with esp-idf-5.x.
But build fails with esp-idf-6.0.

### Actual behavior (suspected bug)

Build failure

### Error logs or terminal output

```shell
LWIP_USE_EXTERNAL_MBEDTLS=1

Build with esp-idf-6.0 , I got below build failure:

In file included from /home/axel/esp/esp-idf/components/lwip/lwip/src/netif/ppp/chap-md5.c:44:
/home/axel/esp/esp-idf/components/lwip/lwip/src/include/netif/ppp/pppcrypt.h:100:10: fatal error: mbedtls/des.h: No such file or directory
  100 | #include "mbedtls/des.h"
```

### Steps to reproduce the behavior

LWIP_USE_EXTERNAL_MBEDTLS=1 and build with IDF-6.0.

### Project release version

latest

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

Ubuntu 24.04

### Shell

Bash

**Comment by david-cermak** [comment]
Hi @AxelLin 

Sorry for the regression, fixing in 20f8b0739c29c43e3030ea84ac3e0595c8c6d068

will close once IDF release branches (v6.0+) reference this commit

**Comment by david-cermak** [comment]
Closing as https://github.com/espressif/esp-lwip/commit/20f8b0739c29c43e3030ea84ac3e0595c8c6d068 is referenced from IDF v6.0/v6.1 with [9c0809ef](https://github.com/espressif/esp-idf/commit/9c0809ef21c433854cea3f0602c768db4dfd4a0f)
